name: audit_life_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  logger: ^2.0.0
  intl: ^0.20.2
  record: ^6.2.0
  permission_handler: ^12.0.1
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  riverpod_generator: ^4.0.0+1
  drift_dev: ^2.16.0
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
